services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
    ports:
     - "8000:8000"
    depends_on:
      - catalogDatabase
    environment:
      AspNetCore_Urls: http://+:8000
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8000
      DatabaseSettings__ConnectionString: mongodb://catalogDatabase:27017
      DatabaseSettings__DatabaseName: CatalogDb
      DatabaseSettings__BrandCollection: Brands
      DatabaseSettings__TypeCollection: Types
      DatabaseSettings__ProductCollection: Products
  catalogDatabase:
    image: mongo
    container_name: catalogDatabase
    restart: always
    ports:
      - "27017:27017"
    volumes:
    - catalogData:/data/db
  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: always
    ports:
        - "6379:6379"
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile
    restart: always
    ports:
      - "8001:8000"
    depends_on: 
      - basketdb
    environment: 
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
      - ASPNETCORE_URLS=http://+:8000
      - CacheSettings__ConnectionString=basketdb:6379
volumes:
  catalogData:
